tasks:
  - init: "gp env HOME=$(pwd)/.home
  && cmake -B/tmp/build -G Ninja
  && cmake --build /tmp/build
  && rm -rf /tmp/build
  "
  - command: gp open cmake.toml
  - command: gp open src/example.cpp

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

vscode:
  extensions:
    - ms-vscode.cmake-tools@1.6.0:lvoCR5usjseB5thI3sZhWA==
