name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-2019, macos-10.15, ubuntu-20.04]
    env:
      BUILD_TYPE: Release
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Compile with gcc 10 on ubuntu
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      run: |
         echo "CC=gcc-10" >> $GITHUB_ENV
         echo "CXX=g++-10" >> $GITHUB_ENV
    - name: Build
      run: |
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        cmake --build build --config ${{ env.BUILD_TYPE }} --parallel
